Debug login from frontend
michaelryanmcneill/shibboleth pull request #53
Opened 2018-08-16 16:30 UTC by Alhrath

Here is a general fix to take into account the situation where the login form is displayed outside the login page, for instance when a theme display a login form in a menu or as a widget.

2019-03-22 14:09 UTC, michaelryanmcneill commented
I would like to get @jrchamp's thoughts on this before approving this PR.

2019-03-22 18:20 UTC, jrchamp commented
I've done some testing on a single site and it's definitely a better experience to have a working login link with an appropriate return_to. However, because `$wp->request` is null on the normal login page, the experience was worse. I found this to be better (overriding the URL only when it was available):

```php
    global $wp;
    $url = false;
    if ( isset( $wp->request ) ) {
        $url = wp_login_url( home_url( $wp->request ) );
    }
    $login_url = add_query_arg( 'action', 'shibboleth', $url );
```

I'll take a look at the experience on multisite and follow up.

2019-03-22 20:19 UTC, jrchamp requested changes
Please change to this so that admin deeplinks with an auth redirect continue to work:
```php
    global $wp;
    $url = false;
    if ( isset( $wp->request ) ) {
        $url = wp_login_url( home_url( $wp->request ) );
    }
    $login_url = add_query_arg( 'action', 'shibboleth', $url );
```

2019-03-28 15:49 UTC, Alhrath commented
Ok like this ?

2019-03-28 18:18 UTC, jrchamp commented
Yes, mostly. There shouldn't be any spaces used to indent, because WordPress uses tabs to indent.

2019-04-12 13:40 UTC, jrchamp approved these changes
Thank you!

To summarize this change: Improve the Shibboleth login link so that when it shows up on a normal request it will correctly still be a login link and will redirect back to the page that showed the login link.

Prior to this change: Shibboleth login links created by this code when on any page other than wp-login.php do not work because they just append action=shibboleth to the request URL.

2019-08-19 19:06 UTC, michaelryanmcneill commented
This looks good to me. Merging.

2019-08-19 19:06 UTC, merged